# Generated by Django 5.1.1 on 2024-11-09 05:40

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True)),
                ('has_registered', models.BooleanField(default=False)),
                ('profileimg', models.ImageField(blank=True, upload_to=users.models.Profile.profile_image_path)),
                ('upi_id', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=10)),
                ('location', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
