# Generated by Django 5.1.1 on 2024-11-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='upi_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
